---
tags: 流程控制
---
结构化程序实际上是由顺序、分支和循环三种基本结构组成的。python 支持三种控制流程：顺序、分支、循环，还支持异常处理流程。

代码默认从上往下顺序执行。

# 分支
根据条件的判断结果，分别执行不同的代码。有单分支、二元分支、多分支。
```Python
if condition:
    pass
[[elif condi2:
    pass
...]
else:
    pass]

# 二分支简写
pass if condition else pass
```

# 循环
如果条件满足，则重复循环执行循环内部代码，直到条件不满足，退出循环。有 for 和 while 循环。

## for 有限循环
```Python
# 次数循环
for i in range(10):
    pass

# 遍历循环 str, list, tuple, dict, set
for e in iterable:
    pass
[else:
    pass]

for i, e in enumerate(iterable):
    pass
[else:
    pass]

# 遍历子列表长度相同的二维列表
for a, b, c in [[e1, e2], [e1, e2]]:
    pass


# 计数循环
for temp in object:
    pass

for i in range(0, 10) | (10):
    pass
    break
else:
    pass

for i in range(10):
    if i == 2:
        continue
    if i == 6:
        break
    print(i)

# 文件遍历
for line in file:
    print(line)


# 累积器循环：计算阶乘 n!
>>> def jiecheng(n):
    	fact = n
    	for factor in range(n-1, 1, -1):
    		fact *= factor
    	return fact

>>> jiecheng(5)
120
```

## while 不定循环
```Python
while condition:
    pass
[else:
    pass]

# 死循环
while True:
    pass


i = 0
while i <= 10:
    pass
    i += 1

i = 0
while i <= 10:
    pass
    break
    i += 1
else:
    pass


active = True
while active:
    pass
    if pass:
        active = False


# 哨兵循环
>>> def calavg():
    	total, count = 0, 0
    	input_str = input("请输入一个数字(按enter完成输入)：")
    	while input_str != "":
    		total += float(input_str)
    		count += 1
    		input_str = input("请输入一个数字(按enter完成输入)：")
    	print("平均值是：{0:0.2f}".format(total / count))

	
>>> calavg()
请输入一个数字(按enter完成输入)：2
请输入一个数字(按enter完成输入)：5
请输入一个数字(按enter完成输入)：8
请输入一个数字(按enter完成输入)：
平均值是：5.00

# 文件循环
>>> total, count = 0, 0
>>> with open(r"C:\Users\yi\Desktop\test.txt") as file_obj:
    	for line in file_obj:
            total += float(line)
            count += 1

			
>>> total, count, total / count
(86.0, 6, 14.333333333333334)

>>> total, count = 0, 0
>>> with open(r"C:\Users\yi\Desktop\test.txt") as file_obj:
    	line = file_obj.readline()
    	while line != "":
    		total += float(line)
    		count += 1
    		line = file_obj.readline()

		
>>> total, count, total / count
(86.0, 6, 14.333333333333334)
```

后测试循环
```PYTHON
>>> number = -1
>>> while number < 0:
    	number = float(input("Enter a positive number: "))
    	if number < 0:
    		print("The number you entered was not positive")

		
Enter a positive number: -9
The number you entered was not positive
Enter a positive number: -5
The number you entered was not positive
Enter a positive number: 6
>>> 
>>> while True:
    	number = float(input("Enter a positive number: "))
    	if number >= 0:
    		break # Exit loop if number is valid.
    	else:
    		print("The number you entered was not positive")

		
Enter a positive number: -7
The number you entered was not positive
Enter a positive number: -8
The number you entered was not positive
Enter a positive number: 4
```

循环加一半
```PYTHON
>>> while True:
    	number = float(input("Enter a positive number: "))
    	if number >= 0: break # Loop exit
    	print("The number you entered was not positive")

	
Enter a positive number: -7
The number you entered was not positive
Enter a positive number: -4
The number you entered was not positive
Enter a positive number: 5
```
## break、continue
break: 退出当前层次的循环，外层循环不受影响。
continue: 跳过当次循环，继续下次循环。

for | while ... else ...：循环执行完毕后，再执行 else 代码，若循环代码中执行了 break，则else 代码不再执行。

嵌套循环中，break只能退出当前的内层循环。

## 循环应用
**计数器、累加器**
通过在循环外部设置 计数变量 和 累加变量，在循环执行中更新变量的值，达到计数和累加的目的。
```Python
count, sum = 0, 0

for i in range(1, 101):
    count += 1
    sum += i

i = 1
while i<101:
    count += 1
    sum += i
    i += 1
```

**枚举解方程**
```Python
# xy*693=yx*396, 枚举求解x,y
x = 1
while x<10:
    y = 1
    while y<10:
        if (x * 10 + y) * 693 == (y * 10 + x) * 396:
            print(x, y)
        y += 1
    x += 1
```

# 异常
## 异常处理
当Python检测到一个错误时，解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的"异常" 。当预见到某个代码块会出现错误时，可使用异常处理。不建议使用大量的 if 结构处理异常。

try中的代码报错，被捕获后，执行except中对捕获到的异常进行处理的代码，这个过程就是捕获异常，保证python解释器能继续执行，程序不崩溃终止。Python为各种异常情况分别定义了内置异常类，发生异常时会自动生成对应异常类对象，交给try结构。
```Python
try:
    code
except xxError:		# 当分别对待异常时，可有多个 except
    pass
except (异常1, 异常2):	# 可捕获多个异常，except (error1, error2, ...)
    pass
except Exception as e:	# 处理所有异常
    print(e)
else:
    pass
finally:
    pass
```

执行逻辑：执行 try 里面的代码，如果存在错误，则捕获异常，执行 except 里面的代码；若不存在错误，则执行 else 里面的代码；无论存不存在错误，都会执行 finally 里的代码。

常见异常：语法错误、逻辑错误
```Python
>>> def my_div(a):
    s = '无结果'
    try:
        s = 10/a
        return s
    except Exception as e:
        print('发生计算错误：', e)
        return '出现异常'
    finally:
        print('函数执行结束')

		
>>> my_div(2)
函数执行结束
5.0
>>> my_div(0)
发生计算错误： division by zero
函数执行结束
'出现异常'
>>> 
>>> 
>>> open("tt.txt", "r")
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    open("tt.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'tt.txt'
>>> 
>>> try:
	open("tt.txt", "r")
except:
	print("捕获异常")

	
捕获异常
>>> 
>>> try:
	open("tt.txt", "r")
except FileNotFoundError as info:
	print("捕获异常:%s" % info)

	
捕获异常:[Errno 2] No such file or directory: 'tt.txt'
>>> 
>>> print(num)
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    print(num)
NameError: name 'num' is not defined
>>> 
>>> try:
	open("tt.txt", "r")
	print(num)
except (FileNotFoundError, NameError) as info:
	print("捕获异常:%s" % info)

	
捕获异常:[Errno 2] No such file or directory: 'tt.txt'
>>> 
>>> try:
	print(num)
	open("tt.txt", "w")
except Exception as info:
	print("捕获异常:%s" % info)
else:
	print("else")
finally:
	print("finally")

	
捕获异常:name 'num' is not defined
finally
```

## 自定义异常
```Python
class AgeError(Exception):
    def __init__(self, age):
        self.age = age

    def __str__(self):
        return "AgeError：你输入的年龄超过范围。age=%d" % self.age

class Person(object):
    def __init__(self, name, age):
        if age > 0 and age <= 150:
            self.name = name
            self.age = age
        else:
            # print("AgeError：你输入的年龄超过范围，age=%d" % age)
            raise AgeError(age)

            # 捕获异常
            # try:
            #     raise AgeError(age)
            # except AgeError as info:
            #     print("捕获异常：%s" % info)


>>> p = Person("刘亦菲", 151)
Traceback (most recent call last):
  File "<pyshell#35>", line 1, in <module>
    p = Person("刘亦菲", 151)
  File "<pyshell#34>", line 7, in __init__
    raise AgeError(age)
AgeError: AgeError：你输入的年龄超过范围。age=151
```